font-family = JetBrains Mono
background = #201d1d
foreground = #fdfcfc
cursor-color = #fdfcfc
cursor-text = #201d1d
selection-background = #fdfcfc
selection-foreground = #201d1d
palette = 0=#201d1d
palette = 1=#ff6961
palette = 2=#30d158
palette = 3=#ff9f0a
palette = 4=#6ab7ff
palette = 5=#d08cff
palette = 6=#64d2ff
palette = 7=#cfcccc
palette = 8=#6e6a6a
palette = 9=#ff453a
palette = 10=#63e87c
palette = 11=#ffd60a
palette = 12=#0a84ff
palette = 13=#bf5af2
palette = 14=#5ac8fa
palette = 15=#fdfcfc
