font-family = JetBrains Mono
background = #fdfcfc
foreground = #201d1d
cursor-color = #201d1d
cursor-text = #fdfcfc
selection-background = #201d1d
selection-foreground = #fdfcfc
palette = 0=#201d1d
palette = 1=#c14b3e
palette = 2=#1f9d61
palette = 3=#b36b00
palette = 4=#007aff
palette = 5=#8957a1
palette = 6=#087f8c
palette = 7=#f1eeee
palette = 8=#646262
palette = 9=#ff3b30
palette = 10=#30a46c
palette = 11=#d97706
palette = 12=#0a84ff
palette = 13=#a855f7
palette = 14=#0891b2
palette = 15=#fdfcfc
